/**
 * MagicDash setup routes — first-launch wizard backend.
 *
 * These routes are PUBLIC (no auth) because they run before MagicDash is
 * configured. They are mounted at `/api/setup/*` in `server.js`.
 *
 *   GET  /api/setup/status      — { needsSetup, hasUsers, hasEnv, demoMode }
 *   POST /api/setup/init-demo   — writes .env from demo template,
 *                                 creates a demo admin user, returns creds
 *
 * Both routes detect first-launch by checking for `MAGICDASH_BOOTSTRAPPED`
 * in `backend/.env`. The bootstrap flag is set by `init-demo` so subsequent
 * status checks return `needsSetup: false`.
 */
import express from 'express';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import bcrypt from 'bcryptjs';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BACKEND_ROOT = path.resolve(__dirname, '..');
const ENV_PATH      = path.join(BACKEND_ROOT, '.env');
const ENV_DEMO_PATH = path.join(BACKEND_ROOT, '.env.demo');
const USERS_PATH    = path.join(BACKEND_ROOT, 'users.json');

const router = express.Router();

function fileExists(p) {
  try { return fs.statSync(p).isFile(); } catch { return false; }
}

function readEnvFile(p) {
  if (!fileExists(p)) return {};
  const raw = fs.readFileSync(p, 'utf-8');
  const out = {};
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq < 0) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

function readUsers() {
  if (!fileExists(USERS_PATH)) return [];
  try { return JSON.parse(fs.readFileSync(USERS_PATH, 'utf-8')); }
  catch { return []; }
}

function isBootstrapped() {
  // Treat as bootstrapped if .env exists AND has either the explicit flag
  // or a JWT_SECRET (proxy for "someone configured this manually").
  if (!fileExists(ENV_PATH)) return false;
  const env = readEnvFile(ENV_PATH);
  if (env.MAGICDASH_BOOTSTRAPPED === 'true') return true;
  if (env.JWT_SECRET && env.JWT_SECRET.length >= 16) return true;
  return false;
}

router.get('/status', (req, res) => {
  const env = readEnvFile(ENV_PATH);
  const users = readUsers();
  res.json({
    needsSetup: !isBootstrapped(),
    hasUsers:   users.length > 0,
    hasEnv:     fileExists(ENV_PATH),
    demoMode:   env.DEMO_MODE === 'true' || process.env.DEMO_MODE === 'true',
  });
});

router.post('/init-demo', async (req, res) => {
  if (isBootstrapped()) {
    return res.status(409).json({ error: 'MagicDash est déjà configuré.' });
  }

  try {
    // 1. Generate a strong JWT secret
    const jwtSecret = crypto.randomBytes(48).toString('hex');

    // 2. Compose .env content from template if available, else minimal demo env
    let envContent;
    if (fileExists(ENV_DEMO_PATH)) {
      envContent = fs.readFileSync(ENV_DEMO_PATH, 'utf-8');
      // Replace placeholder JWT_SECRET line(s)
      if (/^JWT_SECRET=/m.test(envContent)) {
        envContent = envContent.replace(/^JWT_SECRET=.*$/m, `JWT_SECRET=${jwtSecret}`);
      } else {
        envContent += `\nJWT_SECRET=${jwtSecret}\n`;
      }
      // Ensure DEMO_MODE=true is set
      if (/^DEMO_MODE=/m.test(envContent)) {
        envContent = envContent.replace(/^DEMO_MODE=.*$/m, 'DEMO_MODE=true');
      } else {
        envContent += '\nDEMO_MODE=true\n';
      }
    } else {
      envContent = [
        '# Generated by MagicDash setup wizard (demo mode)',
        'DEMO_MODE=true',
        `JWT_SECRET=${jwtSecret}`,
        'PORT=3001',
        '',
      ].join('\n');
    }

    // Stamp the bootstrap flag so we don't re-show the wizard on next launch
    if (!/^MAGICDASH_BOOTSTRAPPED=/m.test(envContent)) {
      envContent += '\nMAGICDASH_BOOTSTRAPPED=true\n';
    }

    fs.writeFileSync(ENV_PATH, envContent, 'utf-8');

    // 3. Create the demo admin user
    const adminEmail    = 'admin@demo.local';
    const adminPassword = 'DemoPass2026';
    const passwordHash  = await bcrypt.hash(adminPassword, 10);

    const users = readUsers();
    const idx = users.findIndex(u => u.email.toLowerCase() === adminEmail);
    const entry = { email: adminEmail, name: 'Demo Admin', passwordHash };
    if (idx >= 0) users[idx] = entry; else users.push(entry);
    fs.writeFileSync(USERS_PATH, JSON.stringify(users, null, 2), 'utf-8');

    // 4. Hot-load the new env into this process so the rest of the app sees it
    //    immediately. Subsequent code paths (auth, demo guards) read from
    //    process.env directly, so this flips behaviour without a restart.
    process.env.DEMO_MODE              = 'true';
    process.env.JWT_SECRET             = jwtSecret;
    process.env.MAGICDASH_BOOTSTRAPPED = 'true';

    res.json({
      ok: true,
      adminEmail,
      adminPassword,
      message: 'Mode démo activé. Connecte-toi avec les identifiants ci-dessus.',
    });
  } catch (err) {
    console.error('[setup/init-demo] failed:', err);
    res.status(500).json({ error: err.message || 'Échec de l\'activation' });
  }
});

export default router;
